### PR TITLE
Add testing users and privileges for unit test support.

### PR DESCRIPTION
**Pull request by guzman-raphael**

### CODE REVIEW

**Review by eywalker — APPROVED** [review]

**Comment by ixcat** [comment]
Wouldn't this be more appropriate as part of the unit test setup phase? 

I could see arguments either way, but having software-specific unit tests assume something about 'standard mysql runtime' seems preferable to having 'standard mysql runtime' assuming something about 'software specific unit tests'..

**Comment by ixcat** [comment]
(realizing I just added assumptions about interactivity to my.cnf; but these were somewhat 'datajoint generic' in purpose)

**Comment by eywalker** [comment]
That's a completely valid point, and this points out why I shouldn't be reviewing and accepting PR in a rush. Let's think about this and revert if necessary.

**Comment by guzman-raphael** [comment]
Thank you guys, for the feedback. Point well taken. Therefore, would it be best to invoke these commands by the nosetest client conditionally if they are necessary?

**Comment by eywalker** [comment]
Yeah I think so. We should keep the Docker container here to be generic.

**Comment by guzman-raphael** [comment]
Sure, I have initiated a revert now for review. Just for my clarification then, what are some use cases that will distinguish this container from the parent container so that I know for the future? Is this meant to be simply a general MySQL container that has been pre-configured?

**Pull request merged**
